# All about qubits
<a id="0"></a> <br>
1. [Codercise I.1.1 - Normalization of quantum states](#1)
2. [Codercise I.1.2  - Inner product and ortonormal bases](#2)
3. [Codercise I.1.3 - A simple quantum algorithm](#3)
4. [Codercise I.1.4 - Applying a quantum operation](#4)
5. [Codercise I.1.5 - A simple quantum algorithm](#5)



<a id="1"></a>
# Codercise I.1.1 - Normalization of quantum states

In [1]:
import numpy as np

In [2]:
def normalize_state(alpha, beta):
    """Compute a normalized quantum state given arbitrary amplitudes.

    Args:
        alpha (complex): The amplitude associated with the |0> state.
        beta (complex): The amplitude associated with the |1> state.

    Returns:
        array[complex]: A vector (numpy array) with 2 elements that represents
        a normalized quantum state.
    """
    """
    inner_product = alpha * np.conjugate(alpha) + beta * np.conjugate(beta)
    norm = np.sqrt(inner_product)

    alpha2, beta2 = alpha/norm, beta/norm

    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1

    return np.array([alpha2,beta2])
    """
    norm = np.linalg.norm([[alpha,beta]])
    normalized_state = np.array([alpha/norm,beta/norm])

    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1

    return normalized_state


*Example:*
Suppose we are given the inputs:

``alpha = 2.0 +1.0j``
``beta = -0.3 + 0.4j``

The function should return the vector

`` np.array([ 0.87287156+0.43643578j, -0.13093073+0.17457431j]) ``


In [3]:
alpha = 2 + 1j
beta = -0.3 + 0.4j
normalize_state(alpha, beta)

array([ 0.87287156+0.43643578j, -0.13093073+0.17457431j])

<a id="2"></a>
# Codercise I.1.2 - Inner product and ortonormal bases
Write a function to compute the inner product between two arbitrary states. Then, use it to verify that |0> and |1> form an orthonormal basis, i.e., the states are normalized and orthogonal.

In [8]:
def inner_product(state_1, state_2):
    """Compute the inner product between two states.

    Args:
        state_1 (array[complex]): A normalized quantum state vector
        state_2 (array[complex]): A second normalized quantum state vector

    Returns:
        complex: The value of the inner product <state_1 | state_2>.
    """
    #inner_product = np.conjugate(state_1) * state_2
    #return inner_product[0] + inner_product[1]

    # COMPUTE AND RETURN THE INNER PRODUCT
    return np.dot(np.conjugate(state_1),state_2)


# Test your results with this code
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

print(f"<0|0> = {inner_product(ket_0, ket_0)}")
print(f"<0|1> = {inner_product(ket_0, ket_1)}")
print(f"<1|0> = {inner_product(ket_1, ket_0)}")
print(f"<1|1> = {inner_product(ket_1, ket_1)}")

<0|0> = 1
<0|1> = 0
<1|0> = 0
<1|1> = 1


<a id="3"></a>
# Codercise I.1.3 - Sampling measurement outcomes
The function below takes a quantum state vector as input. Complete the function to simulate the outcomes of an arbitrary number of quantum measurements, i.e., return a list of samples **0** or **1** based on the probabilities given by the input state.

In [9]:
def measure_state(state, num_meas):
    """Simulate a quantum measurement process.

    Args:
        state (array[complex]): A normalized qubit state vector.
        num_meas (int): The number of measurements to take

    Returns:
        array[int]: A set of num_meas samples, 0 or 1, chosen according to the probability
        distribution defined by the input state.
    """

    prob_0 = np.abs(state[0])**2
    prob_1 = np.abs(state[1])**2
    # COMPUTE THE MEASUREMENT OUTCOME PROBABILITIES

    meas_outcome = np.random.choice(2, num_meas, p = [prob_0.real, prob_1.real])
    # RETURN A LIST OF SAMPLE MEASUREMENT OUTCOMES
    return meas_outcome

Example: Suppose we are given the inputs:
``state_1 = np.array([0.8, 0.6])``
IF we measure q qubit in this state, we'll observe |0> 64% of the time (|0.8|^2 = 0.64) and |1| 36% of the time. Therefore, an example set of 10 measurement outcomes might be:
``[0, 1, 1, 1, 0, 1, 0, 0, 0, 0,]``

In [10]:
state_1 = np.array([0.8, 0.6])
measure_state(state_1, 10)

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 0])

<a id="4"></a>
# Codercise I.1.4 - Applying a quantum operation

In [11]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def apply_u(state):
    """Apply a quantum operation.

    Args:
        state (array[complex]): A normalized quantum state vector.

    Returns:
        array[complex]: The output state after applying U.
    """
    # We can also use builtin python mutliplication operations (e.g. @, .dot, or .matmul) to check the following equation: U\state>
    return  U@state

In [12]:
U = np.array([[0, 1], [1, 0]])
state = np.array([0.8, 0.6])
apply_u(state)

array([0.6, 0.8])

<a id="5"></a>
# Codercise I.1.5 - A simple quantum algorithm

In [14]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)


def initialize_state():
    """Prepare a qubit in state |0>.

    Returns:
        np.array[float]: the vector representation of state |0>.
    """
    # PREPARE THE STATE |0>
    return np.array([1,0])


def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)


def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome


def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.

    Try and do so using three lines of code or less!

    Returns:
        np.array[int]: the measurement results after running the algorithm 100 times
    """

    state = apply_u(initialize_state())

    return measure_state(state, 100)